public with sharing class outerclass {
    
    public inherited sharing class inner1 {
        
        
        
    }
    public without sharing class inner9{
        
    }
    public without sharing class inner8{
        
    }
    public without sharing class inner7{
        
    }
    public without sharing class inner6{
        
    }
    public without sharing class inner5{
        
    }
}